# Generated by Django 6.0 on 2025-12-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
